<div class="heading heading-center mb-3">
      <h2 class="title">Top Selling Products</h2>
      <!-- End .title -->
      <ul class="nav nav-pills nav-border-anim justify-content-center" role="tablist">
         <li class="nav-item">
            <a class="nav-link active" id="top-all-link" data-toggle="tab" href="#top-all-tab" role="tab" aria-controls="top-all-tab" aria-selected="true">All</a>
         </li>
         <li class="nav-item">
            <a class="nav-link" id="top-bags-link" data-toggle="tab" href="#top-bags-tab" role="tab" aria-controls="top-bags-tab" aria-selected="false">Bags</a>
         </li>
         <li class="nav-item">
            <a class="nav-link" id="top-blankets-link" data-toggle="tab" href="#top-blankets-tab" role="tab" aria-controls="top-blankets-tab" aria-selected="false">Blankets</a>
         </li>
         <li class="nav-item">
            <a class="nav-link" id="top-jwellery-link" data-toggle="tab" href="#top-jwellery-tab" role="tab" aria-controls="top-jwellery-tab" aria-selected="false">jwellery</a>
         </li>
      </ul>
</div>
   <!-- End .heading -->
   <div class="tab-content">
      <div class="tab-pane p-0 fade show active" id="top-all-tab" role="tabpanel" aria-labelledby="top-all-link">
         <div class="products">
            <div class="row justify-content-center">
               <div class="col-6 col-md-4 col-lg-3 col-xl-5col">
                  <div class="product product-11 text-center">
                     <figure class="product-media">
                        <img src="assets/images/theme/products/allproduct/bag1.jpg" alt="Product image" class="product-image">
                     </figure>
                     <!-- End .product-media -->
                     <div class="product-action">
                        <a href="#" class="btn-product btn-cart"><span><i class="fa fa-shopping-bag"></i>
                        Bags</span></a>
                     </div>
                     <!-- End .product-action -->
                  </div>
                  <!-- End .product -->
               </div>
               <!-- End .col-sm-6 col-md-4 col-lg-3 -->
               <div class="col-6 col-md-4 col-lg-3 col-xl-5col">
                  <div class="product product-11 text-center">
                     <figure class="product-media">
                        <img src="assets/images/theme/products/allproduct/blankets1.jpg" alt="Product image" class="product-image">
                     </figure>
                     <!-- End .product-media -->
                     <div class="product-action">
                        <a href="#" class="btn-product btn-cart"><span><i class="fa fa-shopping-bag"></i>
                        Blankets</span></a>
                     </div>
                     <!-- End .product-action -->
                  </div>
                  <!-- End .product -->
                </div>
               <!-- End .col-sm-6 col-md-4 col-lg-3 -->
               <div class="col-6 col-md-4 col-lg-3 col-xl-5col">
                  <div class="product product-11 text-center">
                     <figure class="product-media">
                        <img src="assets/images/theme/products/allproduct/jwellery1.jpg" alt="Product image" class="product-image">
                     </figure>
                     <!-- End .product-media -->
                     <div class="product-action">
                        <a href="#" class="btn-product btn-cart"><span><i class="fa fa-shopping-bag"></i>
                        Jwellery</span></a>
                     </div>
                     <!-- End .product-action -->
                  </div>
                  <!-- End .product -->
               </div>
               <!-- End .col-sm-6 col-md-4 col-lg-3 -->
               <div class="col-6 col-md-4 col-lg-3 col-xl-5col">
                  <div class="product product-11 text-center">
                     <figure class="product-media">
                        <img src="assets/images/theme/products/allproduct/carpet1.jpg" alt="Product image" class="product-image">
                     </figure>
                     <!-- End .product-media -->
                     <div class="product-action">
                        <a href="#" class="btn-product btn-cart"><span><i class="fa fa-shopping-bag"></i>
                        Carpets</span></a>
                     </div>
                     <!-- End .product-action -->
                  </div>
                  <!-- End .product -->
               </div>
               <!-- End .col-sm-6 col-md-4 col-lg-3 -->
               <div class="col-6 col-md-4 col-lg-3 col-xl-5col">
                  <div class="product product-11 text-center">
                     <figure class="product-media">
                        <img src="assets/images/theme/products/allproduct/bag2.jpg" alt="Product image" class="product-image">
                     </figure>
                     <!-- End .product-media -->
                     <div class="product-action">
                        <a href="#" class="btn-product btn-cart"><span><i class="fa fa-shopping-bag"></i>
                        Bags</span></a>
                     </div>
                     <!-- End .product-action -->
                  </div>
                  <!-- End .product -->
               </div>
               <!-- End .col-sm-6 col-md-4 col-lg-3 -->
            </div>
            <!-- End .row -->
         </div>
         <!-- End .products -->
      </div>
      <!-- .End .tab-pane -->
      <div class="tab-pane p-0 fade" id="top-bags-tab" role="tabpanel" aria-labelledby="top-bags-link">
         <div class="products">
            <div class="row justify-content-center">
               <div class="col-6 col-md-4 col-lg-3 col-xl-5col">
                  <div class="product product-11 text-center">
                     <figure class="product-media">
                        <img src="assets/images/theme/products/bags/11.jpg" alt="Product image" class="product-image">
                     </figure>
                     <!-- End .product-media -->
                     <div class="product-action">
                        <a href="#" class="btn-product btn-cart"><span><i class="fa fa-shopping-bag"></i>
                        Bags</span></a>
                     </div>
                     <!-- End .product-action -->
                  </div>
                  <!-- End .product -->
               </div>
               <!-- End .col-sm-6 col-md-4 col-lg-3 -->
               <div class="col-6 col-md-4 col-lg-3 col-xl-5col">
                  <div class="product product-11 text-center">
                     <figure class="product-media">
                        <img src="assets/images/theme/products/bags/bag1.jpg" alt="Product image" class="product-image">
                     </figure>
                     <!-- End .product-media -->
                     <div class="product-action">
                        <a href="#" class="btn-product btn-cart"><span><i class="fa fa-shopping-bag"></i>
                        Bags</span></a>
                     </div>
                     <!-- End .product-action -->
                  </div>
                  <!-- End .product -->
               </div>
               <!-- End .col-sm-6 col-md-4 col-lg-3 -->
               <div class="col-6 col-md-4 col-lg-3 col-xl-5col">
                  <div class="product product-11 text-center">
                     <figure class="product-media">
                        <img src="assets/images/theme/products/bags/bag4.jpg" alt="Product image" class="product-image">
                     </figure>
                     <!-- End .product-media -->
                     <div class="product-action">
                        <a href="#" class="btn-product btn-cart"><span><i class="fa fa-shopping-bag"></i>
                        Bags</span></a>
                     </div>
                     <!-- End .product-action -->
                  </div>
                  <!-- End .product -->
               </div>
               <!-- End .col-sm-6 col-md-4 col-lg-3 -->
               <div class="col-6 col-md-4 col-lg-3 col-xl-5col">
                  <div class="product product-11 text-center">
                     <figure class="product-media">
                        <img src="assets/images/theme/products/bags/bag5.jpg" alt="Product image" class="product-image">
                     </figure>
                     <!-- End .product-media -->
                     <div class="product-action">
                        <a href="#" class="btn-product btn-cart"><span><i class="fa fa-shopping-bag"></i>
                        Bags</span></a>
                     </div>
                     <!-- End .product-action -->
                  </div>
                  <!-- End .product -->
               </div>
               <!-- End .col-sm-6 col-md-4 col-lg-3 -->
               <div class="col-6 col-md-4 col-lg-3 col-xl-5col">
                  <div class="product product-11 text-center">
                     <figure class="product-media">
                        <img src="assets/images/theme/products/bags/bag7.jpg" alt="Product image" class="product-image">
                     </figure>
                     <!-- End .product-media -->
                     <div class="product-action">
                        <a href="#" class="btn-product btn-cart"><span><i class="fa fa-shopping-bag"></i>
                        Bags</span></a>
                     </div>
                     <!-- End .product-action -->
                  </div>
                  <!-- End .product -->
               </div>
               <!-- End .col-sm-6 col-md-4 col-lg-3 -->
            </div>
            <!-- End .row -->
         </div>
         <!-- End .products -->
      </div>
      <!-- .End .tab-pane -->
      <div class="tab-pane p-0 fade" id="top-blankets-tab" role="tabpanel" aria-labelledby="top-blankets-link">
         <div class="products">
            <div class="row justify-content-center">
               <div class="col-6 col-md-4 col-lg-3 col-xl-5col">
                  <div class="product product-11 text-center">
                     <figure class="product-media">
                        <img src="assets/images/theme/products/blankets/1.jpg" alt="Product image" class="product-image">
                     </figure>
                     <!-- End .product-media -->
                     <div class="product-action">
                        <a href="#" class="btn-product btn-cart"><span><i class="fa fa-shopping-bag"></i>
                        Blankets</span></a>
                     </div>
                     <!-- End .product-action -->
                  </div>
                  <!-- End .product -->
               </div>
               <!-- End .col-sm-6 col-md-4 col-lg-3 -->
               <div class="col-6 col-md-4 col-lg-3 col-xl-5col">
                  <div class="product product-11 text-center">
                     <figure class="product-media">
                        <img src="assets/images/theme/products/blankets/2.jpg" alt="Product image" class="product-image">
                     </figure>
                     <!-- End .product-media -->
                     <div class="product-action">
                        <a href="#" class="btn-product btn-cart"><span><i class="fa fa-shopping-bag"></i>
                        Blankets</span></a>
                     </div>
                     <!-- End .product-action -->
                  </div>
                  <!-- End .product -->
               </div>
               <!-- End .col-sm-6 col-md-4 col-lg-3 -->
               <div class="col-6 col-md-4 col-lg-3 col-xl-5col">
                  <div class="product product-11 text-center">
                     <figure class="product-media">
                        <img src="assets/images/theme/products/blankets/3.jpg" alt="Product image" class="product-image">
                     </figure>
                     <!-- End .product-media -->
                     <div class="product-action">
                        <a href="#" class="btn-product btn-cart"><span><i class="fa fa-shopping-bag"></i>
                        Blankets</span></a>
                     </div>
                     <!-- End .product-action -->
                  </div>
                  <!-- End .product -->
               </div>
               <!-- End .col-sm-6 col-md-4 col-lg-3 -->
               <div class="col-6 col-md-4 col-lg-3 col-xl-5col">
                  <div class="product product-11 text-center">
                     <figure class="product-media">
                        <img src="assets/images/theme/products/blankets/4.jpg" alt="Product image" class="product-image">
                     </figure>
                     <!-- End .product-media -->
                     <div class="product-action">
                        <a href="#" class="btn-product btn-cart"><span><i class="fa fa-shopping-bag"></i>
                        Blankets</span></a>
                     </div>
                     <!-- End .product-action -->
                  </div>
                  <!-- End .product -->
               </div>
               <!-- End .col-sm-6 col-md-4 col-lg-3 -->
               <div class="col-6 col-md-4 col-lg-3 col-xl-5col">
                  <div class="product product-11 text-center">
                     <figure class="product-media">
                        <img src="assets/images/theme/products/blankets/5.html" alt="Product image" class="product-image">
                     </figure>
                     <!-- End .product-media -->
                     <div class="product-action">
                        <a href="#" class="btn-product btn-cart"><span><i class="fa fa-shopping-bag"></i>
                        Blankets</span></a>
                     </div>
                     <!-- End .product-action -->
                  </div>
                  <!-- End .product -->
               </div>
               <!-- End .col-sm-6 col-md-4 col-lg-3 -->
            </div>
            <!-- End .row -->
         </div>
         <!-- End .products -->
      </div>
      <!-- .End .tab-pane -->
      <div class="tab-pane p-0 fade" id="top-jwellery-tab" role="tabpanel" aria-labelledby="top-jwellery-link">
         <div class="products">
            <div class="row justify-content-center">
               <div class="col-6 col-md-4 col-lg-3 col-xl-5col">
                  <div class="product product-11 text-center">
                     <figure class="product-media">
                        <img src="assets/images/theme/products/jwellery/jw1.jpg" alt="Product image" class="product-image">
                     </figure>
                     <!-- End .product-media -->
                     <div class="product-action">
                        <a href="#" class="btn-product btn-cart"><span><i class="fa fa-shopping-bag"></i>
                        jwellery</span></a>
                     </div>
                     <!-- End .product-action -->
                  </div>
                  <!-- End .product -->
               </div>
               <!-- End .col-sm-6 col-md-4 col-lg-3 -->
               <div class="col-6 col-md-4 col-lg-3 col-xl-5col">
                  <div class="product product-11 text-center">
                     <figure class="product-media">
                        <img src="assets/images/theme/products/jwellery/jw2.jpg" alt="Product image" class="product-image">
                     </figure>
                     <!-- End .product-media -->
                     <div class="product-action">
                        <a href="#" class="btn-product btn-cart"><span><i class="fa fa-shopping-bag"></i>
                        jwellery</span></a>
                     </div>
                     <!-- End .product-action -->
                  </div>
                  <!-- End .product -->
               </div>
               <!-- End .col-sm-6 col-md-4 col-lg-3 -->
               <div class="col-6 col-md-4 col-lg-3 col-xl-5col">
                  <div class="product product-11 text-center">
                     <figure class="product-media">
                        <img src="assets/images/theme/products/jwellery/jw3.jpg" alt="Product image" class="product-image">
                     </figure>
                     <!-- End .product-media -->
                     <div class="product-action">
                        <a href="#" class="btn-product btn-cart"><span><i class="fa fa-shopping-bag"></i>
                        jwellery</span></a>
                     </div>
                     <!-- End .product-action -->
                  </div>
                  <!-- End .product -->
               </div>
               <!-- End .col-sm-6 col-md-4 col-lg-3 -->
               <div class="col-6 col-md-4 col-lg-3 col-xl-5col">
                  <div class="product product-11 text-center">
                     <figure class="product-media">
                        <img src="assets/images/theme/products/jwellery/jw4.jpg" alt="Product image" class="product-image">
                     </figure>
                     <!-- End .product-media -->
                     <div class="product-action">
                        <a href="#" class="btn-product btn-cart"><span><i class="fa fa-shopping-bag"></i>
                        jwellery</span></a>
                     </div>
                     <!-- End .product-action -->
                  </div>
                  <!-- End .product -->
               </div>
               <!-- End .col-sm-6 col-md-4 col-lg-3 -->
               <div class="col-6 col-md-4 col-lg-3 col-xl-5col">
                  <div class="product product-11 text-center">
                     <figure class="product-media">
                        <img src="assets/images/theme/products/jwellery/jw5.jpg" alt="Product image" class="product-image">
                     </figure>
                     <!-- End .product-media -->
                     <div class="product-action">
                        <a href="#" class="btn-product btn-cart"><span><i class="fa fa-shopping-bag"></i>
                        jwellery</span></a>
                     </div>
                     <!-- End .product-action -->
                  </div>
                  <!-- End .product -->
               </div>
               <!-- End .col-sm-6 col-md-4 col-lg-3 -->
            </div>
            <!-- End .row -->
         </div>
         <!-- End .products -->
      </div>
      <!-- .End .tab-pane -->
   </div>
   <!-- End .tab-content -->